<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Choose your location</name>
   <tag></tag>
   <elementGuidId>02a75fbf-6a15-4e55-bd70-d0178bf2aee6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a-popover-header-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='a-popover-header-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>516e3451-4279-4281-9646-380919839272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-popover-header-content</value>
      <webElementGuid>175122f1-a13d-4eef-9663-0a3f8b0bf0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-popover-header-1</value>
      <webElementGuid>7c748282-37b0-4969-a572-99a90b1f9875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose your location</value>
      <webElementGuid>b7f9a151-6217-4f88-bd06-d25291efc739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-popover-header-1&quot;)</value>
      <webElementGuid>4c4ebb22-64db-470b-9e37-ce110831676d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='a-popover-header-1']</value>
      <webElementGuid>107686e7-0831-4a9b-ae83-bb0e93d54c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-1']/div/header/h4</value>
      <webElementGuid>0af81b4e-8aab-4707-8868-7f77c7d2993e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>d65f4274-715e-4b91-830f-88ba63673c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'a-popover-header-1' and (text() = 'Choose your location' or . = 'Choose your location')]</value>
      <webElementGuid>2f5a3857-e51d-4a96-8d0c-c3002a806d06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
