<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputGLUXZipUpdateInput</name>
   <tag></tag>
   <elementGuidId>99844479-1fb3-4833-aa50-6070139acf11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GLUXZipUpdateInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GLUXZipUpdateInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44a12653-e2a1-4be0-9d6f-0346ac43278f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GLUX_Full_Width a-declarative</value>
      <webElementGuid>3cbe015c-78c7-40be-a646-d25bfdbfd6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>072334f1-7288-4604-865c-c572437cc45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>09d2cc5c-f495-4e70-b463-ad69191c6bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GLUXZipUpdateInput</value>
      <webElementGuid>88647733-c84e-4ca6-b669-738c2f99f9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>or enter an Indian pincode</value>
      <webElementGuid>504c1c90-2e64-4ddb-a818-746f8365eac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>GLUXPostalInputAction</value>
      <webElementGuid>90b3b280-fed7-4aa8-bd65-7921e293acb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GLUXZipUpdateInput&quot;)</value>
      <webElementGuid>3d4a034a-8660-4ba7-87fa-be48eb47afb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GLUXZipUpdateInput']</value>
      <webElementGuid>c97ee357-a68a-4a4e-b5c1-96ae67fb2292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GLUXZipInputSection']/div/input</value>
      <webElementGuid>6cb78b10-789a-4b7e-8cb3-97b89e6b039d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>d37581cc-e7bf-482e-89bb-53056a680bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'GLUXZipUpdateInput']</value>
      <webElementGuid>6b504610-543c-4c37-998e-2fba88e15743</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
