<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Delivering to Chennai 600003</name>
   <tag></tag>
   <elementGuidId>44b4ae45-427f-407b-baa0-3fedc8274061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#glow-ingress-line1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c942498c-da55-46de-a7cc-69c95896e7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-line-1 nav-progressive-content</value>
      <webElementGuid>ee2f9a73-f015-4672-9ee2-a5da018cbb64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>glow-ingress-line1</value>
      <webElementGuid>1cd00b1c-92aa-4b7c-900a-14ce7be4de78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                   Delivering to Chennai 600003
                </value>
      <webElementGuid>bb8bc02e-f536-466a-b2dc-5b95cd8798ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;glow-ingress-line1&quot;)</value>
      <webElementGuid>93a7d29d-2499-452c-a5ef-a8a64f2441de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='glow-ingress-line1']</value>
      <webElementGuid>fc2a646f-b284-4651-add8-c4d56d2fadd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='glow-ingress-block']/span</value>
      <webElementGuid>c048eea4-988b-4bf2-b402-3c3c38ccfbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/span</value>
      <webElementGuid>b68c4cf7-706d-4955-af35-b7d6f78b4626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'glow-ingress-line1' and (text() = '
                   Delivering to Chennai 600003
                ' or . = '
                   Delivering to Chennai 600003
                ')]</value>
      <webElementGuid>a4dbca0a-e73e-42d8-b30c-5112e9704704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
