<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Featured</name>
   <tag></tag>
   <elementGuidId>41ed344f-b9cb-47f4-844d-d84e04e1131b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a-popover-9 > div.a-popover-wrapper > div.a-popover-inner > ul.a-nostyle.a-list-link > li.a-dropdown-item > #s-result-sort-select_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='s-result-sort-select_0'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>590ed734-4e75-45e5-b253-68e2bf90f55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b86f8175-0a78-42b2-8127-50db71d664a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>e1d64f70-b3cf-4729-b22f-59a5ea8bbd70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ee97d747-76fc-4c99-9d49-548c48a31a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;relevanceblender&quot;}</value>
      <webElementGuid>43720c6c-da4d-4cbd-8da7-bdc87917d53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>s-result-sort-select_0</value>
      <webElementGuid>ec60916b-bff4-413b-b279-c0c387f15eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>9b9c3020-b478-4334-ac82-ecf9913b11f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Featured</value>
      <webElementGuid>00df4e7f-c30f-48af-b502-41f50a69be6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-popover-9&quot;)/div[@class=&quot;a-popover-wrapper&quot;]/div[@class=&quot;a-popover-inner&quot;]/ul[@class=&quot;a-nostyle a-list-link&quot;]/li[@class=&quot;a-dropdown-item&quot;]/a[@id=&quot;s-result-sort-select_0&quot;]</value>
      <webElementGuid>95acf200-fb17-468c-98bd-0b12a0573eae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='s-result-sort-select_0'])[5]</value>
      <webElementGuid>2d056ab9-006f-4e94-a940-8c65bfad6e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-9']/div/div/ul/li/a</value>
      <webElementGuid>3d79a406-c9c1-407f-be84-65528f1417e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Featured')])[5]</value>
      <webElementGuid>6101530e-6ec1-4fac-8fa0-699419b6ea37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[39]</value>
      <webElementGuid>300d9c11-a944-4a2f-8b2a-c8b349fc5bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/ul/li/a</value>
      <webElementGuid>97ed5495-dfd1-46b9-a4a2-6c394831c4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 's-result-sort-select_0' and (text() = 'Featured' or . = 'Featured')]</value>
      <webElementGuid>1e37ae25-04fd-4318-85f0-0a14b9ef877e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
