<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Price High to Low</name>
   <tag></tag>
   <elementGuidId>06918b4f-85e9-42e3-ad54-4d85fef7fcd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a-popover-5 > div.a-popover-wrapper > div.a-popover-inner > ul.a-nostyle.a-list-link > li.a-dropdown-item > #s-result-sort-select_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='s-result-sort-select_2'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>187ffac8-881a-45c6-99d9-b15427e006e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7e8c709e-6c28-4d75-853f-8e4f6f932d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>e0806a01-dc1f-4120-aaa4-d4a7902ce46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>30296737-e4de-4707-94cc-e572056ae204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;price-desc-rank&quot;}</value>
      <webElementGuid>c851fffe-bf78-4485-abc9-45568c621056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>s-result-sort-select_2</value>
      <webElementGuid>8f640d70-6372-435c-9321-1dfb78204ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>bc308125-b665-4cbf-b4a0-b3746bbdfd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Price: High to Low</value>
      <webElementGuid>b58b38fa-52b3-41d2-9dad-96ef811eb0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-popover-5&quot;)/div[@class=&quot;a-popover-wrapper&quot;]/div[@class=&quot;a-popover-inner&quot;]/ul[@class=&quot;a-nostyle a-list-link&quot;]/li[@class=&quot;a-dropdown-item&quot;]/a[@id=&quot;s-result-sort-select_2&quot;]</value>
      <webElementGuid>5bce9c56-60e3-490d-a873-be05fa67d76c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='s-result-sort-select_2'])[2]</value>
      <webElementGuid>5b22bae9-3507-4c1e-96cf-39c235138c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-5']/div/div/ul/li[3]/a</value>
      <webElementGuid>74544b2b-1291-4374-b875-3cdba522828a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Price: High to Low')])[2]</value>
      <webElementGuid>ce4768e1-0405-417f-9694-51a9835dc38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[27]</value>
      <webElementGuid>46042bca-ba56-4270-b5ca-b62db98f9fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/ul/li[3]/a</value>
      <webElementGuid>4996c31a-0481-4422-83ca-e2b4af0a60b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 's-result-sort-select_2' and (text() = 'Price: High to Low' or . = 'Price: High to Low')]</value>
      <webElementGuid>bba6e2cc-2a6a-4904-9fd8-5035971063d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
