<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Custom Products_nav-imageHref</name>
   <tag></tag>
   <elementGuidId>47ca7d56-5442-4d29-9d5f-9319aeb37fd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-imageHref</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navSwmHoliday']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f2fa85c-59d1-49da-9496-cbec618afb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>New Launches from Mobile, Electronics &amp; more</value>
      <webElementGuid>7ff30418-f4e4-433b-8564-81dbcc2c60df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/b/?_encoding=UTF8&amp;node=56944732031&amp;ref_=nav_swm_swm_gd&amp;pf_rd_p=2c882b5b-152a-4b19-a642-4683a15fc4f7&amp;pf_rd_s=nav-sitewide-msg&amp;pf_rd_t=4201&amp;pf_rd_i=navbar-4201&amp;pf_rd_m=A21TJRUUN4KGV&amp;pf_rd_r=1J692QWV82ZG8JJSNMXR</value>
      <webElementGuid>06c6d8b8-19c6-40e0-b8c5-c3ebfeab0e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-imageHref</value>
      <webElementGuid>286cffb2-f5c2-4bae-aa21-5e1b8805f31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3e6fea34-869f-4526-b7bf-9178e1d8995b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navSwmHoliday&quot;)/a[@class=&quot;nav-imageHref&quot;]</value>
      <webElementGuid>8b8cc6be-23b6-43b0-a6c1-9738e1b9ad1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navSwmHoliday']/a</value>
      <webElementGuid>74013e73-3ba9-46b6-b9ca-c1f7338a58bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/b/?_encoding=UTF8&amp;node=56944732031&amp;ref_=nav_swm_swm_gd&amp;pf_rd_p=2c882b5b-152a-4b19-a642-4683a15fc4f7&amp;pf_rd_s=nav-sitewide-msg&amp;pf_rd_t=4201&amp;pf_rd_i=navbar-4201&amp;pf_rd_m=A21TJRUUN4KGV&amp;pf_rd_r=1J692QWV82ZG8JJSNMXR')]</value>
      <webElementGuid>d75e2b30-acec-488f-965c-8d5a7e29e2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/div/a</value>
      <webElementGuid>93a346a5-6b6b-4af9-a2c6-848d63bd9453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/b/?_encoding=UTF8&amp;node=56944732031&amp;ref_=nav_swm_swm_gd&amp;pf_rd_p=2c882b5b-152a-4b19-a642-4683a15fc4f7&amp;pf_rd_s=nav-sitewide-msg&amp;pf_rd_t=4201&amp;pf_rd_i=navbar-4201&amp;pf_rd_m=A21TJRUUN4KGV&amp;pf_rd_r=1J692QWV82ZG8JJSNMXR']</value>
      <webElementGuid>597747f2-b281-42be-a59f-aa8e9fb9ab08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
