<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>aattach-close_sideSheet-link</name>
   <tag></tag>
   <elementGuidId>bf639042-6dcf-4786-bc5a-3a1a01cd3f76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attach-close_sideSheet-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='attach-close_sideSheet-link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05d623de-fbca-42ac-947d-2c8b8e6e7ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attach-close_sideSheet-link</value>
      <webElementGuid>3c0ab5b8-498e-48c6-bb96-5aa6d6126284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Exit this panel and return to the product page. </value>
      <webElementGuid>35c9a8c2-0f08-4512-b23f-7e6583e7efdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal close-button</value>
      <webElementGuid>d45a1b21-e9f9-481f-8e24-79b04c5683f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d8a3f969-eefd-4815-9496-7c8a42b67f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attach-close_sideSheet-link&quot;)</value>
      <webElementGuid>af2c2755-d539-4827-9379-74fe1ed3a45b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='attach-close_sideSheet-link']</value>
      <webElementGuid>7e7847ab-85f4-43b7-9714-d51dcd7ec1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attach-accessory-pane']/div/div/a</value>
      <webElementGuid>ef3b762c-275e-4bd9-9fda-7aecd391573c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[92]</value>
      <webElementGuid>353d497d-6564-4fca-9c87-48c46501bd4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/a</value>
      <webElementGuid>8efca01b-f979-4afe-88e8-a8ca89d8d31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'attach-close_sideSheet-link' and @href = '#']</value>
      <webElementGuid>473c79f6-091e-4af0-b7ad-cef7b876b813</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
