<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>7241cc84-a8e2-4b39-bb42-ef0147007712</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.a-checkbox.a-checkbox-fancy.s-navigation-checkbox.aok-float-left > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='p_89/Samsung']/span/a/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4e0a7249-2334-48d4-a8e8-12c4f6f3a572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p_89/Samsung&quot;)/span[@class=&quot;a-list-item&quot;]/a[@class=&quot;a-link-normal s-navigation-item&quot;]/div[@class=&quot;a-checkbox a-checkbox-fancy s-navigation-checkbox aok-float-left&quot;]/label[1]</value>
      <webElementGuid>366fdf57-a483-43fd-b77c-3a5559c22069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='p_89/Samsung']/span/a/div/label</value>
      <webElementGuid>888a5681-ea4f-4858-ac71-78fb156ac847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/label</value>
      <webElementGuid>616ad6a0-15f0-4b9f-a855-b52e89add778</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
