<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contact Us</name>
   <tag></tag>
   <elementGuidId>3b8cfd92-e1b0-48d8-b11d-c047ba76a782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.cs-help-gateway-cu-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='GUID-5EE29096-6777-4579-8347-A1AC0FBE386A__LI_99011713B541404D9D28504B63F88387']/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>baddb69d-71a7-4619-ab96-36a9742ce391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cs-help-gateway-cu-btn</value>
      <webElementGuid>61257d80-188a-4f98-bc3a-d2c4c6235ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.in/gp/help/customer/contact-us/ref=hp_gt_comp_cu?nodeId=200507590</value>
      <webElementGuid>49a3cc6e-384a-493a-82ad-204a58ef1c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>0a5d6977-c1e4-4ef8-a2d6-58aa7e103698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact Us</value>
      <webElementGuid>23722cd7-da45-4c7b-9f15-cccc66d91b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;help-gateway-category-12&quot;)/div[@class=&quot;a-row&quot;]/div[@class=&quot;cat-links-container&quot;]/div[@class=&quot;a-column&quot;]/ul[@class=&quot;category-list a-nostyle a-list-link&quot;]/li[@id=&quot;GUID-5EE29096-6777-4579-8347-A1AC0FBE386A__LI_99011713B541404D9D28504B63F88387&quot;]/span[@class=&quot;a-list-item&quot;]/a[@class=&quot;cs-help-gateway-cu-btn&quot;]</value>
      <webElementGuid>caaa0686-9a0d-4010-9e2a-39825dc138ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='GUID-5EE29096-6777-4579-8347-A1AC0FBE386A__LI_99011713B541404D9D28504B63F88387']/span/a</value>
      <webElementGuid>01610ce7-e18f-4352-9b18-c374b7d66626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Contact Us')]</value>
      <webElementGuid>dd417689-aa1f-4b7b-b3b2-796285ea8b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.in/gp/help/customer/contact-us/ref=hp_gt_comp_cu?nodeId=200507590')]</value>
      <webElementGuid>59a4e4af-1029-4752-9600-6177b59f51a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div/ul/li[6]/span/a</value>
      <webElementGuid>e0068c1e-b911-4c63-a9e0-024a73516258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.amazon.in/gp/help/customer/contact-us/ref=hp_gt_comp_cu?nodeId=200507590' and (text() = 'Contact Us' or . = 'Contact Us')]</value>
      <webElementGuid>fb892d6c-4e50-43ee-9ae7-e643a78edb08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
