<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_nav-flyout-buffer-top</name>
   <tag></tag>
   <elementGuidId>e7817d51-464d-41d3-9eee-cb7dbb5a45f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-flyout-accountList > div.nav-flyout-buffer-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-flyout-accountList']/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b0bbfad-9879-417f-99ef-65d8d69ec99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-flyout-buffer-top</value>
      <webElementGuid>7fbaf041-2927-451b-b798-428a34c2d015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-accountList&quot;)/div[@class=&quot;nav-flyout-buffer-top&quot;]</value>
      <webElementGuid>843a48a4-835c-4ef0-824c-8cf1ca85b076</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-accountList']/div[5]</value>
      <webElementGuid>f79fd530-defe-447d-ba7b-bfe026e5d4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]</value>
      <webElementGuid>807fbb89-cdcd-4afd-837f-2feb8d2cb2cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
