<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divnav-cover</name>
   <tag></tag>
   <elementGuidId>7d5d3827-84a4-4d18-b0e0-559c1965ab08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-cover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-cover']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cb67c8cf-a04a-4a12-b75c-425e6d958803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-cover</value>
      <webElementGuid>de967d66-0f7c-408c-9f41-356e86540675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-cover&quot;)</value>
      <webElementGuid>29329663-e10f-40b7-b606-5c48e576b944</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nav-cover']</value>
      <webElementGuid>3251672b-3850-40b3-be0e-d01d83861d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/div[8]</value>
      <webElementGuid>2f25922a-4336-4cbb-8d9a-7b1f1e807af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]</value>
      <webElementGuid>78087bff-fed2-491a-a1a2-b42302706a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nav-cover']</value>
      <webElementGuid>26aa939e-2104-4de3-a7ba-56b0125ca7e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
